#!/bin/bash

GREEN="\e[32m"
RED="\e[31m"
BLUE="\e[34m"
RESET="\e[0m"

#General info
echo -e "==General info=="

echo -e "${RED}Current user:${RESET} $(whoami)"
chasis=$(hostnamectl | sed -n 's/^[[:space:]]*Chassis:[[:space:]]*//p')
#Move until true in sed (regex)
os_name=$(cat /etc/os-release | grep -i pretty | sed 's/[^"]*//; s/"//g')
echo -e "${RED}Distro name:${RESET} ${os_name}"
shell=${SHELL}
echo -e "${RED}Shell:${RESET} ${shell##*/}"
echo -e "${RED}Chassis: ${RESET}${chasis} -> ${BLUE}\"Chassis\" refers to the physical or virtual hardware type of the system${RESET}"
echo -e "${RED}Machine ID: ${RESET}$(hostnamectl | sed -n 's/^[[:space:]]*Machine ID:[[:space:]]*//p')"
echo -e "${RED}Vendor: ${RESET}$(hostnamectl | sed -n 's/^[[:space:]]*Hardware Vendor:[[:space:]]*//p')"
echo -e "${RED}Hardware Model (Use this to search for the device on internet): ${RESET}$(hostnamectl | sed -n 's/^[[:space:]]*Hardware Model:[[:space:]]*//p')"
echo -e "${RED}System language:${RESET} ${LANG}"
echo -e "${RED}Terminal:${RESET} ${TERM}"
echo -e "${RED}Window manager:${RESET} ${XDG_CURRENT_DESKTOP}"
echo -e "${RED}Session:${RESET} ${XDG_SESSION_TYPE}"
upTime=$(uptime -p)
echo -e "${RED}Machine running time:${RESET} ${upTime#* }"

# Kernel version + archi
echo -e "\n==Kernel info=="
echo -e "${RED}Kernel version:${RESET} $(uname -s), $(uname -r)"

#Disk
echo -e "\n==Disk=="
USER_ACC=/home/$(whoami)
echo -e "${RED}Root filesystem:${RESET} $(df -h / | awk 'NR==2 {print $1}')"
echo -e "${RED}Current user filesystem:${RESET} $(df -h ${USER_ACC} | awk 'NR==2 {print $1}')"
echo -e "${RED}Total disk space:${RESET} $(df -h ${USER_ACC} | awk 'NR==2 {print $2}')"
echo -e "${RED}Total used space:${RESET} $(df -h ${USER_ACC} | awk 'NR==2 {print $3", Total: "$5}')"
echo -e "${RED}Remaining disk space:${RESET} $(df -h ${USER_ACC} | awk 'NR==2 {print $4}')"

#Memory
echo -e "\n==Memory=="
echo -e "${RED}Currently used memory:${RESET} $(free -h | awk 'NR==2 {print $3}')"
echo -e "${RED}Currently available memory:${RESET} $(free -h | awk 'NR==2 {print $7}')"
echo -e "${RED}Swap used:${RESET} $(free -h | awk 'NR==3 {print $3}')"
echo -e "${RED}Swap free:${RESET} $(free -h | awk 'NR==3 {print $4}')"

#CPU info --> /proc/cpuinfo
echo -e "\n==CPU=="
cpuModel=$(cat /proc/cpuinfo | grep 'model name' /proc/cpuinfo | head -1 | cut -d: -f2)
echo -e "${RED}Model Name:${RESET} ${cpuModel#* }"
echo -e "${RED}CPU Archi type:${RESET} $(uname -m)"
thread_per_core=$(lscpu | grep -i thread | sed 's/[^0-9]//g')
total_num_of_cores_per_socket=$(lscpu | grep -i "^core" | sed 's/[^0-9]//g')
total_num_of_sockets=$(lscpu | grep -i "^socket" | sed 's/[^0-9]//g')
total_core=$((total_num_of_cores_per_socket * total_num_of_sockets))
total_threads=$((total_core * thread_per_core))
echo -e "${RED}CPU total cores:${RESET} ${total_core}"
echo -e "${RED}CPU total threads:${RESET} ${total_threads}"
#Temp
cpu_temp=$(for zone in /sys/class/thermal/thermal_zone*; do
  if [[ $(cat "$zone/type") == "x86_pkg_temp" ]]; then
    awk '{print $1/1000 "°C"}' "$zone/temp"
  fi
done)

echo -e "${RED}CPU Temp:${RESET} $cpu_temp -> ${BLUE}Note: Temperature detection may not be accurate on all systems.
If a value appears, it is likely correct, but you should verify
your CPU thermal zone or sensor configuration.${RESET}"

#GPU info
echo -e "\n==GPU=="
##list pci devices
## IFS = internal field separator --> It used to split word in bash, it's a default value, I turn it off here to not allow separation by space
echo -e "${BLUE}More information about GPU's could be found by installing \"lshw\"${RESET}"
i=1
while IFS= read -r line; do
  echo -e "${RED}GPU number ${i} used:${RESET}${line##*:}"
  ((i += 1))
done < <(lspci | grep -i vga)
((i -= 1))
echo -e "${RED}Number of GPU's:${RESET} ${i}"

#Networking
echo -e "\n==Networking=="
echo -e "${RED}Hostname:${RESET} $(cat /etc/hostname)"
echo -e "${RED}IP address (wifi):${RESET} $(ip a | grep wlan0 | grep inet | awk '{print $2}')"
echo -e "${RED}IP address (ethernet):${RESET} $(ip a | grep enp | grep inet | awk '{print $2}')"
